forge "https://forgeapi.puppetlabs.com"

####################### NOTE #############################
# All modules *must* be pinned to a specific version/tag #
##########################################################

# Not included in nubis-base yet...
mod 'nubis/nubis_apache',
    :git => 'https://github.com/nubisproject/nubis-puppet-apache.git',
    :ref => 'v0.1.5'
